# Proyecto RappiPlus: de datos a decisiones de negocio

**Introducción**


El objetivo de este proyecto es evaluar el desempeño del servicio **RappiPlus** para apoyar **decisiones de negocio basadas en datos**.

Se trabajan con múltiples datasets del negocio:

- **rappiplus_orders_raw.csv** → información de pedidos, precios, descuentos y revenue  
- **rappiplus_catalog.csv** → costos de productos, categorías y proveedores  
- **rappiplus_marketing_spend.csv** → inversión en marketing por canal y país  
- **events / users / user_activity (SQL)** → comportamiento del usuario dentro de la plataforma  
- **experiment_checkout_ui.csv** → resultados de un experimento A/B en el checkout  

El análisis sigue una lógica clara y progresiva:

1. 🔍 Evaluar si podemos confiar en los datos (calidad de datos en Python) 

2. 💰 Analizar si el negocio es rentable (revenue, costos y profit)  

3. 🛒 Entender dónde se pierden los usuarios (funnel de conversión)  

4. 🔁 Evaluar si los usuarios regresan (retención por cohortes)  

5. 🧪 Validar si los cambios generan impacto (test estadístico)  

6. 📊 Comunicar los resultados (dashboard en BI)  

A lo largo del proyecto, se transforman datos en insights para responder preguntas clave del negocio y proponer **recomendaciones accionables**.

---

## 🔹 Paso 1: Cargar y validar la calidad de los datos

---

### 1.1 Carga de datos y vista rápida

**🎯 Objetivo:** Familiarizarte con la estructura de los datasets del negocio antes de analizarlos.

**Instrucciones:**

- Importa las librerías necesarias
- Carga los archivos:
  - `rappiplus_orders_raw.csv`
  - `rappiplus_catalog.csv`
  - `rappiplus_marketing_spend.csv`
- Guarda los DataFrames en:
  - `orders`, `catalog`, `marketing`
- Explora cada dataset.

---

In [1]:
# importar librerías
import pandas as pd
import numpy as np

In [2]:
# cargar archivos

orders = pd.read_csv('https://practicum-content.s3.amazonaws.com/datasets/rappiplus_orders_raw.csv')

catalog = pd.read_csv('https://practicum-content.s3.amazonaws.com/datasets/rappiplus_catalog.csv')

marketing = pd.read_csv('https://practicum-content.s3.amazonaws.com/datasets/rappiplus_marketing_spend.csv')

In [3]:
# explorar datasets
print('ORDERS')
display(orders.head())
print('Dimensiones:', orders.shape)

print('\nCATALOG')
display(catalog.head())
print('Dimensiones:', catalog.shape)

print('\nMARKETING')
display(marketing.head())
print('Dimensiones:', marketing.shape)

ORDERS

,id_pedido,id_usuario,fecha_hora_pedido,pais,dispositivo,fuente_referencia,nombre_producto,categoria_producto,cantidad,precio_unitario,monto_descuento,monto_total
0,order_0,user_6993,2025-05-22,Argentina,desktop,organic,Jacket-Winter-M,Moda,2.0,332.69,0.0,665.37
1,order_1,user_1329,2025-06-15,Mexico,desktop,paid_search,Tablet-Standard-64GB,Electronica,1.0,176.86,5.0,171.86
2,order_2,user_3194,2025-05-02,Argentina,desktop,social,Blender-XL-Red,Hogar,2.0,102.99,10.0,195.99
3,order_3,user_4510,2025-06-09,Colombia,mobile,social,Tablet-Standard-64GB,Electronica,1.0,257.87,15.0,242.87
4,order_4,user_5044,2025-03-30,Argentina,desktop,paid_search,Blender-XL-Red,Hogar,1.0,336.28,0.0,336.28

Dimensiones: (25100, 12)

CATALOG

,nombre_producto,categoria_producto,costo_unitario,proveedor
0,Laptop-Gaming-16GB,Electrónica,280.68,"Fuller, Pena and Myers"
1,Phone-Pro-128GB,Electrónica,10.12,King Ltd
2,Tablet-Standard-64GB,Electrónica,25.21,Bowers LLC
3,Blender-XL-Red,Hogar,176.64,Long-Reid
4,Vacuum-Pro-Black,Hogar,16.60,"Rivera, Carr and Finley"

Dimensiones: (7, 4)

MARKETING

        fecha      pais            id_campaña        canal    gasto
0  2025-01-01    Mexico        organic_Mexico      organic  2446.25
1  2025-01-01    Mexico    paid_search_Mexico  paid_search  2704.34
2  2025-01-01    Mexico         social_Mexico       social  2045.01
3  2025-01-01  Colombia      organic_Colombia      organic  2597.21
4  2025-01-01  Colombia  paid_search_Colombia  paid_search  1771.40

Dimensiones: (1620, 5)

In [4]:
# tipos de datos

print('Tipos de datos - ORDERS')
print(orders.dtypes)

print('\nTipos de datos - CATALOG')
print(catalog.dtypes)

print('\nTipos de datos - MARKETING')
print(marketing.dtypes)

Tipos de datos - ORDERS
id_pedido              object
id_usuario             object
fecha_hora_pedido      object
pais                   object
dispositivo            object
fuente_referencia      object
nombre_producto        object
categoria_producto     object
cantidad              float64
precio_unitario       float64
monto_descuento       float64
monto_total           float64
dtype: object

Tipos de datos - CATALOG
nombre_producto        object
categoria_producto     object
costo_unitario        float64
proveedor              object
dtype: object

Tipos de datos - MARKETING
fecha          object
pais           object
id_campaña     object
canal          object
gasto         float64
dtype: object

In [5]:
# valores ausentes

print('Valores ausentes - ORDERS')
print(orders.isna().sum())

print('\nValores ausentes - CATALOG')
print(catalog.isna().sum())

print('\nValores ausentes - MARKETING')
print(marketing.isna().sum())

Valores ausentes - ORDERS
id_pedido               0
id_usuario              0
fecha_hora_pedido       0
pais                  300
dispositivo            20
fuente_referencia      30
nombre_producto        30
categoria_producto     80
cantidad               50
precio_unitario        50
monto_descuento        50
monto_total             0
dtype: int64

Valores ausentes - CATALOG
nombre_producto       0
categoria_producto    0
costo_unitario        0
proveedor             0
dtype: int64

Valores ausentes - MARKETING
fecha           0
pais            0
id_campaña      0
canal         101
gasto           0
dtype: int64

---

## Observaciones iniciales

Se cargaron los tres datasets correspondientes al proyecto: pedidos (orders), catálogo de productos (catalog) e inversión en marketing (marketing).

El dataset orders contiene 25,100 registros y 12 columnas. El dataset catalog contiene 7 registros y 4 columnas, mientras que marketing contiene 1,620 registros y 5 columnas.

En la revisión inicial se identificaron valores ausentes en algunas variables de orders y en la variable canal de marketing. El dataset catalog no presenta valores ausentes.

Las variables de fecha de orders y marketing están almacenadas inicialmente como tipo object, por lo que posteriormente se convertirán al formato de fecha correspondiente.

Esta revisión inicial permite identificar los principales aspectos que deberán evaluarse durante la etapa de limpieza y validación de los datos.

### Revisión y calidad de datos

**🎯 Objetivo:** Detectar y corregir problemas en los datos que puedan afectar el análisis de revenue, costos y rentabilidad.

Se revisan los 3 datasets
- Validar y convertir fechas al formato correcto  
- Revisar variables numéricas (sin negativos o ceros inválidos)  
- Verificar consistencia de montos  
- Eliminar duplicados  
- Revisar variables categóricas 

---

In [6]:
# tu código aquí
print('Duplicados en ORDERS:', orders.duplicated().sum())
print('Duplicados en CATALOG:', catalog.duplicated().sum())
print('Duplicados en MARKETING:', marketing.duplicated().sum())

Duplicados en ORDERS: 100
Duplicados en CATALOG: 0
Duplicados en MARKETING: 0

In [7]:
# Revisar los registros duplicados de orders

duplicados_orders = orders[orders.duplicated(keep=False)]

print('Cantidad de registros involucrados en duplicados:', len(duplicados_orders))

display(duplicados_orders.sort_values('id_pedido').head(20))

Cantidad de registros involucrados en duplicados: 200

,id_pedido,id_usuario,fecha_hora_pedido,pais,dispositivo,fuente_referencia,nombre_producto,categoria_producto,cantidad,precio_unitario,monto_descuento,monto_total
25023,order_10082,user_690,2025-02-17,Argentina,desktop,social,Sneakers-Urban-42,Moda,2.0,221.34,0.0,442.67
10082,order_10082,user_690,2025-02-17,Argentina,desktop,social,Sneakers-Urban-42,Moda,2.0,221.34,0.0,442.67
25037,order_10709,user_6783,2025-02-16,Colombia,mobile,organic,Jacket-Winter-M,Moda,1.0,170.10,10.0,160.10
10709,order_10709,user_6783,2025-02-16,Colombia,mobile,organic,Jacket-Winter-M,Moda,1.0,170.10,10.0,160.10
25065,order_10829,user_7697,2025-01-23,Argentina,mobile,social,Phone-Pro-128GB,Electronica,2.0,115.54,0.0,231.08
10829,order_10829,user_7697,2025-01-23,Argentina,mobile,social,Phone-Pro-128GB,Electronica,2.0,115.54,0.0,231.08
10856,order_10856,user_1899,2025-03-18,Colombia,desktop,social,Laptop-Gaming-16GB,Electronica,1.0,72.53,0.0,72.53
25044,order_10856,user_1899,2025-03-18,Colombia,desktop,social,Laptop-Gaming-16GB,Electronica,1.0,72.53,0.0,72.53
11449,order_11449,user_1480,2025-03-21,Mexico,desktop,paid_search,Vacuum-Pro-Black,Hogar,1.0,60.55,5.0,55.55
25083,order_11449,user_1480,2025-03-21,Mexico,desktop,paid_search,Vacuum-Pro-Black,Hogar,1.0,60.55,5.0,55.55
11537,order_11537,user_3115,2025-03-08,Argentina,desktop,organic,Vacuum-Pro-Black,Hogar,1.0,147.20,5.0,142.20
25003,order_11537,user_3115,2025-03-08,Argentina,desktop,organic,Vacuum-Pro-Black,Hogar,1.0,147.20,5.0,142.20
11623,order_11623,user_2157,2025-06-25,Mexico,desktop,organic,Vacuum-Pro-Black,Hogar,2.0,285.59,5.0,566.18
25015,order_11623,user_2157,2025-06-25,Mexico,desktop,organic,Vacuum-Pro-Black,Hogar,2.0,285.59,5.0,566.18
25090,order_11645,user_7098,2025-01-12,Colombia,mobile,paid_search,Tablet-Standard-64GB,Electronica,1.0,140.86,0.0,140.86
11645,order_11645,user_7098,2025-01-12,Colombia,mobile,paid_search,Tablet-Standard-64GB,Electronica,1.0,140.86,0.0,140.86
11863,order_11863,user_5847,2025-06-07,Mexico,mobile,social,Blender-XL-Red,Hogar,1.0,189.04,10.0,179.04
25030,order_11863,user_5847,2025-06-07,Mexico,mobile,social,Blender-XL-Red,Hogar,1.0,189.04,10.0,179.04
11954,order_11954,user_1350,2025-06-01,Argentina,mobile,social,Jacket-Winter-M,Moda,1.0,170.79,5.0,165.79
25011,order_11954,user_1350,2025-06-01,Argentina,mobile,social,Jacket-Winter-M,Moda,1.0,170.79,5.0,165.79

In [8]:
# Revisar IDs de pedido duplicados

print('IDs de pedido duplicados:', orders['id_pedido'].duplicated().sum())

display(
    orders[orders['id_pedido'].duplicated(keep=False)]
    .sort_values('id_pedido')
    .head(20)
)

IDs de pedido duplicados: 100

,id_pedido,id_usuario,fecha_hora_pedido,pais,dispositivo,fuente_referencia,nombre_producto,categoria_producto,cantidad,precio_unitario,monto_descuento,monto_total
25023,order_10082,user_690,2025-02-17,Argentina,desktop,social,Sneakers-Urban-42,Moda,2.0,221.34,0.0,442.67
10082,order_10082,user_690,2025-02-17,Argentina,desktop,social,Sneakers-Urban-42,Moda,2.0,221.34,0.0,442.67
25037,order_10709,user_6783,2025-02-16,Colombia,mobile,organic,Jacket-Winter-M,Moda,1.0,170.10,10.0,160.10
10709,order_10709,user_6783,2025-02-16,Colombia,mobile,organic,Jacket-Winter-M,Moda,1.0,170.10,10.0,160.10
25065,order_10829,user_7697,2025-01-23,Argentina,mobile,social,Phone-Pro-128GB,Electronica,2.0,115.54,0.0,231.08
10829,order_10829,user_7697,2025-01-23,Argentina,mobile,social,Phone-Pro-128GB,Electronica,2.0,115.54,0.0,231.08
10856,order_10856,user_1899,2025-03-18,Colombia,desktop,social,Laptop-Gaming-16GB,Electronica,1.0,72.53,0.0,72.53
25044,order_10856,user_1899,2025-03-18,Colombia,desktop,social,Laptop-Gaming-16GB,Electronica,1.0,72.53,0.0,72.53
11449,order_11449,user_1480,2025-03-21,Mexico,desktop,paid_search,Vacuum-Pro-Black,Hogar,1.0,60.55,5.0,55.55
25083,order_11449,user_1480,2025-03-21,Mexico,desktop,paid_search,Vacuum-Pro-Black,Hogar,1.0,60.55,5.0,55.55
11537,order_11537,user_3115,2025-03-08,Argentina,desktop,organic,Vacuum-Pro-Black,Hogar,1.0,147.20,5.0,142.20
25003,order_11537,user_3115,2025-03-08,Argentina,desktop,organic,Vacuum-Pro-Black,Hogar,1.0,147.20,5.0,142.20
11623,order_11623,user_2157,2025-06-25,Mexico,desktop,organic,Vacuum-Pro-Black,Hogar,2.0,285.59,5.0,566.18
25015,order_11623,user_2157,2025-06-25,Mexico,desktop,organic,Vacuum-Pro-Black,Hogar,2.0,285.59,5.0,566.18
25090,order_11645,user_7098,2025-01-12,Colombia,mobile,paid_search,Tablet-Standard-64GB,Electronica,1.0,140.86,0.0,140.86
11645,order_11645,user_7098,2025-01-12,Colombia,mobile,paid_search,Tablet-Standard-64GB,Electronica,1.0,140.86,0.0,140.86
11863,order_11863,user_5847,2025-06-07,Mexico,mobile,social,Blender-XL-Red,Hogar,1.0,189.04,10.0,179.04
25030,order_11863,user_5847,2025-06-07,Mexico,mobile,social,Blender-XL-Red,Hogar,1.0,189.04,10.0,179.04
11954,order_11954,user_1350,2025-06-01,Argentina,mobile,social,Jacket-Winter-M,Moda,1.0,170.79,5.0,165.79
25011,order_11954,user_1350,2025-06-01,Argentina,mobile,social,Jacket-Winter-M,Moda,1.0,170.79,5.0,165.79

In [9]:
# Eliminar registros duplicados de orders

orders = orders.drop_duplicates().copy()

print('Dimensiones después de eliminar duplicados:', orders.shape)
print('Duplicados restantes:', orders.duplicated().sum())

Dimensiones después de eliminar duplicados: (25000, 12)
Duplicados restantes: 0

In [10]:
# REVISIÓN DE FECHAS
# ======================

# Convertir columnas de fecha al tipo datetime
orders['fecha_hora_pedido'] = pd.to_datetime(
    orders['fecha_hora_pedido'],
    errors='coerce'
)

marketing['fecha'] = pd.to_datetime(
    marketing['fecha'],
    errors='coerce'
)

# Revisar tipos de datos después de la conversión
print('Tipo de dato - fecha_hora_pedido:')
print(orders['fecha_hora_pedido'].dtype)

print('\nTipo de dato - fecha:')
print(marketing['fecha'].dtype)

# Revisar valores nulos después de la conversión
print('\nFechas inválidas o ausentes en ORDERS:')
print(orders['fecha_hora_pedido'].isna().sum())

print('\nFechas inválidas o ausentes en MARKETING:')
print(marketing['fecha'].isna().sum())

# Revisar rango de fechas
print('\nRango de fechas - ORDERS:')
print('Fecha mínima:', orders['fecha_hora_pedido'].min())
print('Fecha máxima:', orders['fecha_hora_pedido'].max())

print('\nRango de fechas - MARKETING:')
print('Fecha mínima:', marketing['fecha'].min())
print('Fecha máxima:', marketing['fecha'].max())

Tipo de dato - fecha_hora_pedido:
datetime64[ns]

Tipo de dato - fecha:
datetime64[ns]

Fechas inválidas o ausentes en ORDERS:
0

Fechas inválidas o ausentes en MARKETING:
0

Rango de fechas - ORDERS:
Fecha mínima: 2025-01-01 00:00:00
Fecha máxima: 2025-06-30 00:00:00

Rango de fechas - MARKETING:
Fecha mínima: 2025-01-01 00:00:00
Fecha máxima: 2025-06-29 00:00:00

## Observaciones sobre la validación de fechas

Las columnas fecha_hora_pedido del dataset orders y fecha del dataset marketing fueron convertidas correctamente al formato datetime.

Después de la conversión no se identificaron valores nulos, por lo que no se detectaron fechas inválidas en ninguno de los dos datasets.

El período de análisis de orders comprende del 1 de enero de 2025 al 30 de junio de 2025, mientras que los datos de marketing abarcan del 1 de enero de 2025 al 29 de junio de 2025.

Se observa una diferencia de un día en la fecha máxima disponible entre ambas fuentes. En esta etapa se registra esta diferencia como una variación en la cobertura temporal de los datasets, sin asumir que represente un error o una relación causal.

In [11]:
# REVISIÓN DE VARIABLES NUMÉRICAS
# ======================

# Variables numéricas por dataset
numericas_orders = [
    'cantidad',
    'precio_unitario',
    'monto_descuento',
    'monto_total'
]

numericas_catalog = [
    'costo_unitario'
]

numericas_marketing = [
    'gasto'
]

# Revisar estadísticas descriptivas
print('ESTADÍSTICAS - ORDERS')
display(orders[numericas_orders].describe())

print('\nESTADÍSTICAS - CATALOG')
display(catalog[numericas_catalog].describe())

print('\nESTADÍSTICAS - MARKETING')
display(marketing[numericas_marketing].describe())


# ======================
# REVISIÓN DE VALORES NEGATIVOS
# ======================

print('\nVALORES NEGATIVOS - ORDERS')

for columna in numericas_orders:
    negativos = (orders[columna] < 0).sum()
    print(f'{columna}: {negativos}')

print('\nVALORES NEGATIVOS - CATALOG')

for columna in numericas_catalog:
    negativos = (catalog[columna] < 0).sum()
    print(f'{columna}: {negativos}')

print('\nVALORES NEGATIVOS - MARKETING')

for columna in numericas_marketing:
    negativos = (marketing[columna] < 0).sum()
    print(f'{columna}: {negativos}')


# ======================
# REVISIÓN DE CEROS
# ======================

print('\nVALORES EN CERO - ORDERS')

for columna in numericas_orders:
    ceros = (orders[columna] == 0).sum()
    print(f'{columna}: {ceros}')

print('\nVALORES EN CERO - CATALOG')

for columna in numericas_catalog:
    ceros = (catalog[columna] == 0).sum()
    print(f'{columna}: {ceros}')

print('\nVALORES EN CERO - MARKETING')

for columna in numericas_marketing:
    ceros = (marketing[columna] == 0).sum()
    print(f'{columna}: {ceros}')

ESTADÍSTICAS - ORDERS

           cantidad  precio_unitario  monto_descuento   monto_total
count  24950.000000     24950.000000     24950.000000  2.500000e+04
mean       7.115110       259.374527         4.502605  2.079498e+03
std      296.869961       138.690738         5.224057  9.914760e+04
min       -2.000000        20.030000         0.000000 -4.926500e+02
25%        1.000000       138.470000         0.000000  1.806700e+02
50%        2.000000       258.795000         0.000000  3.418050e+02
75%        2.000000       380.377500        10.000000  5.185800e+02
max    20000.000000       499.960000        15.000000  8.840200e+06

ESTADÍSTICAS - CATALOG

       costo_unitario
count        7.000000
mean       102.252857
std        111.011563
min         10.120000
25%         16.905000
50%         25.210000
75%        182.975000
max        280.680000

ESTADÍSTICAS - MARKETING

            gasto
count  1620.00000
mean   1772.74292
std     734.43294
min     501.11000
25%    1128.03000
50%    1782.42500
75%    2420.68500
max    2999.36000

VALORES NEGATIVOS - ORDERS
cantidad: 4
precio_unitario: 0
monto_descuento: 0
monto_total: 4

VALORES NEGATIVOS - CATALOG
costo_unitario: 0

VALORES NEGATIVOS - MARKETING
gasto: 0

VALORES EN CERO - ORDERS
cantidad: 0
precio_unitario: 0
monto_descuento: 12498
monto_total: 0

VALORES EN CERO - CATALOG
costo_unitario: 0

VALORES EN CERO - MARKETING
gasto: 0

In [12]:
# REVISIÓN DE REGISTROS NUMÉRICOS PROBLEMÁTICOS
# ======================

# Registros con cantidad negativa
print('REGISTROS CON CANTIDAD NEGATIVA')
display(
    orders[orders['cantidad'] < 0]
)

# Registros con monto total negativo
print('\nREGISTROS CON MONTO TOTAL NEGATIVO')
display(
    orders[orders['monto_total'] < 0]
)

# Registros con cantidades mayores a 10
print('\nREGISTROS CON CANTIDAD MAYOR A 10')
display(
    orders[orders['cantidad'] > 10]
    .sort_values('cantidad', ascending=False)
)

REGISTROS CON CANTIDAD NEGATIVA

,id_pedido,id_usuario,fecha_hora_pedido,pais,dispositivo,fuente_referencia,nombre_producto,categoria_producto,cantidad,precio_unitario,monto_descuento,monto_total
266,order_266,user_7011,2025-03-13,NaN,desktop,paid_search,Phone-Pro-128GB,Electronica,-2.0,101.31,10.0,-192.62
267,order_267,user_1087,2025-05-07,NaN,desktop,social,Phone-Pro-128GB,Electronica,-1.0,43.50,5.0,-38.50
268,order_268,user_84,2025-02-19,NaN,desktop,organic,Phone-Pro-128GB,Electronica,-1.0,497.65,5.0,-492.65
269,order_269,user_3323,2025-05-25,NaN,desktop,paid_search,Phone-Pro-128GB,Electronica,-1.0,423.53,0.0,-423.53

REGISTROS CON MONTO TOTAL NEGATIVO

,id_pedido,id_usuario,fecha_hora_pedido,pais,dispositivo,fuente_referencia,nombre_producto,categoria_producto,cantidad,precio_unitario,monto_descuento,monto_total
266,order_266,user_7011,2025-03-13,NaN,desktop,paid_search,Phone-Pro-128GB,Electronica,-2.0,101.31,10.0,-192.62
267,order_267,user_1087,2025-05-07,NaN,desktop,social,Phone-Pro-128GB,Electronica,-1.0,43.50,5.0,-38.50
268,order_268,user_84,2025-02-19,NaN,desktop,organic,Phone-Pro-128GB,Electronica,-1.0,497.65,5.0,-492.65
269,order_269,user_3323,2025-05-25,NaN,desktop,paid_search,Phone-Pro-128GB,Electronica,-1.0,423.53,0.0,-423.53

REGISTROS CON CANTIDAD MAYOR A 10

,id_pedido,id_usuario,fecha_hora_pedido,pais,dispositivo,fuente_referencia,nombre_producto,categoria_producto,cantidad,precio_unitario,monto_descuento,monto_total
3656,order_3656,user_884,2025-01-01,Argentina,mobile,organic,Laptop-Gaming-16GB,Electronica,20000.0,297.66,0.0,5953200.0
3668,order_3668,user_7270,2025-06-24,Mexico,mobile,paid_search,Laptop-Gaming-16GB,Electronica,20000.0,348.31,0.0,6966200.0
3722,order_3722,user_4723,2025-05-09,Argentina,mobile,paid_search,Laptop-Gaming-16GB,Electronica,20000.0,442.01,0.0,8840200.0
3726,order_3726,user_2536,2025-02-12,Colombia,desktop,social,Laptop-Gaming-16GB,Electronica,20000.0,290.85,0.0,5817000.0
3521,order_3521,user_5812,2025-02-03,Mexico,mobile,paid_search,Laptop-Gaming-16GB,Electronica,10000.0,43.14,0.0,431400.0
3522,order_3522,user_3575,2025-03-29,Argentina,desktop,social,Laptop-Gaming-16GB,Electronica,10000.0,280.55,0.0,2805500.0
3586,order_3586,user_3380,2025-02-03,Mexico,mobile,paid_search,Laptop-Gaming-16GB,Electronica,10000.0,490.35,0.0,4903500.0
3643,order_3643,user_4440,2025-01-07,Colombia,desktop,social,Laptop-Gaming-16GB,Electronica,10000.0,238.15,0.0,2381500.0
3689,order_3689,user_6566,2025-06-16,mexico,desktop,paid_search,Laptop-Gaming-16GB,Electronica,10000.0,87.69,0.0,876900.0
3748,order_3748,user_7096,2025-02-23,Mexico,desktop,organic,Laptop-Gaming-16GB,Electronica,10000.0,336.93,0.0,3369300.0

In [13]:

# DISTRIBUCIÓN DE CANTIDAD
# ======================

cantidad_frecuencia = (
    orders['cantidad']
    .value_counts(dropna=False)
    .sort_index()
)

display(cantidad_frecuencia)

-2.0            1
-1.0            3
 1.0        12345
 2.0        12591
 10000.0        6
 20000.0        4
 NaN           50
Name: cantidad, dtype: int64

In [14]:
# REGISTROS CON CANTIDADES ALTAS
# ======================

cantidad_alta = (
    orders[orders['cantidad'] >= 10]
    ['cantidad']
    .value_counts()
    .sort_index()
)

print('Frecuencia de cantidades mayores o iguales a 10:')
display(cantidad_alta)

Frecuencia de cantidades mayores o iguales a 10:

10000.0    6
20000.0    4
Name: cantidad, dtype: int64

In [15]:
# REVISIÓN DE PRODUCTOS CON CANTIDADES ALTAS
# ======================

productos_cantidad_alta = (
    orders[orders['cantidad'] >= 10]
    .groupby('nombre_producto')
    .agg(
        registros=('id_pedido', 'count'),
        cantidad_min=('cantidad', 'min'),
        cantidad_max=('cantidad', 'max')
    )
    .sort_values('cantidad_max', ascending=False)
)

display(productos_cantidad_alta)

                    registros  cantidad_min  cantidad_max
nombre_producto
Laptop-Gaming-16GB         10       10000.0       20000.0

In [16]:
# REVISIÓN DETALLADA DE VALORES EXTREMOS
# ======================

valores_extremos = orders[
    orders['cantidad'].isin([10000, 20000])
].copy()

display(
    valores_extremos[
        [
            'id_pedido',
            'id_usuario',
            'fecha_hora_pedido',
            'pais',
            'nombre_producto',
            'cantidad',
            'precio_unitario',
            'monto_descuento',
            'monto_total'
        ]
    ].sort_values('cantidad', ascending=False)
)

,id_pedido,id_usuario,fecha_hora_pedido,pais,nombre_producto,cantidad,precio_unitario,monto_descuento,monto_total
3656,order_3656,user_884,2025-01-01,Argentina,Laptop-Gaming-16GB,20000.0,297.66,0.0,5953200.0
3668,order_3668,user_7270,2025-06-24,Mexico,Laptop-Gaming-16GB,20000.0,348.31,0.0,6966200.0
3722,order_3722,user_4723,2025-05-09,Argentina,Laptop-Gaming-16GB,20000.0,442.01,0.0,8840200.0
3726,order_3726,user_2536,2025-02-12,Colombia,Laptop-Gaming-16GB,20000.0,290.85,0.0,5817000.0
3521,order_3521,user_5812,2025-02-03,Mexico,Laptop-Gaming-16GB,10000.0,43.14,0.0,431400.0
3522,order_3522,user_3575,2025-03-29,Argentina,Laptop-Gaming-16GB,10000.0,280.55,0.0,2805500.0
3586,order_3586,user_3380,2025-02-03,Mexico,Laptop-Gaming-16GB,10000.0,490.35,0.0,4903500.0
3643,order_3643,user_4440,2025-01-07,Colombia,Laptop-Gaming-16GB,10000.0,238.15,0.0,2381500.0
3689,order_3689,user_6566,2025-06-16,mexico,Laptop-Gaming-16GB,10000.0,87.69,0.0,876900.0
3748,order_3748,user_7096,2025-02-23,Mexico,Laptop-Gaming-16GB,10000.0,336.93,0.0,3369300.0

In [17]:
# INFORMACIÓN DEL PRODUCTO EN EL CATÁLOGO
# ======================

display(
    catalog[
        catalog['nombre_producto'] == 'Laptop-Gaming-16GB'
    ]
)

,nombre_producto,categoria_producto,costo_unitario,proveedor
0,Laptop-Gaming-16GB,Electrónica,280.68,"Fuller, Pena and Myers"

In [18]:
# VALIDACIÓN DE CONSISTENCIA DE MONTOS
# ======================

# Calcular el monto esperado
orders['monto_calculado'] = (
    orders['cantidad'] * orders['precio_unitario']
) - orders['monto_descuento']

# Calcular la diferencia entre el monto registrado
# y el monto calculado
orders['diferencia_monto'] = (
    orders['monto_total'] - orders['monto_calculado']
)

# Identificar registros donde la diferencia
# sea mayor a una pequeña tolerancia por redondeo
inconsistentes_monto = orders[
    orders['diferencia_monto'].abs() > 0.01
]

print('Total de registros:', len(orders))
print('Registros con inconsistencias en el monto:', len(inconsistentes_monto))

# Mostrar los registros inconsistentes
display(
    inconsistentes_monto[
        [
            'id_pedido',
            'cantidad',
            'precio_unitario',
            'monto_descuento',
            'monto_total',
            'monto_calculado',
            'diferencia_monto'
        ]
    ].head(20)
)

Total de registros: 25000
Registros con inconsistencias en el monto: 1145

,id_pedido,cantidad,precio_unitario,monto_descuento,monto_total,monto_calculado,diferencia_monto
2,order_2,2.0,102.99,10.0,195.99,195.98,0.01
24,order_24,2.0,117.99,0.0,235.99,235.98,0.01
35,order_35,2.0,467.34,5.0,929.69,929.68,0.01
41,order_41,2.0,37.77,10.0,65.53,65.54,-0.01
136,order_136,2.0,211.05,15.0,407.09,407.10,-0.01
180,order_180,2.0,451.16,15.0,887.31,887.32,-0.01
261,order_261,2.0,209.33,10.0,408.65,408.66,-0.01
266,order_266,-2.0,101.31,10.0,-192.62,-212.62,20.00
267,order_267,-1.0,43.50,5.0,-38.50,-48.50,10.00
268,order_268,-1.0,497.65,5.0,-492.65,-502.65,10.00
270,order_270,2.0,127.95,0.0,255.89,255.90,-0.01
281,order_281,2.0,100.68,0.0,201.35,201.36,-0.01
290,order_290,2.0,41.92,5.0,78.83,78.84,-0.01
297,order_297,2.0,79.93,10.0,149.85,149.86,-0.01
319,order_319,2.0,471.22,5.0,937.43,937.44,-0.01
330,order_330,2.0,183.52,0.0,367.03,367.04,-0.01
398,order_398,2.0,386.66,5.0,768.31,768.32,-0.01
418,order_418,2.0,42.36,5.0,79.71,79.72,-0.01
423,order_423,2.0,144.86,5.0,284.71,284.72,-0.01
432,order_432,2.0,49.57,5.0,94.13,94.14,-0.01

In [19]:
# VALIDACIÓN CORREGIDA DE MONTOS
# ======================

# Calcular el monto esperado
orders['monto_calculado'] = (
    orders['cantidad'] * orders['precio_unitario']
) - orders['monto_descuento']

# Redondear ambos montos a 2 decimales
orders['monto_total_redondeado'] = (
    orders['monto_total'].round(2)
)

orders['monto_calculado_redondeado'] = (
    orders['monto_calculado'].round(2)
)

# Calcular diferencia después del redondeo
orders['diferencia_monto'] = (
    orders['monto_total_redondeado']
    - orders['monto_calculado_redondeado']
)

# Identificar inconsistencias reales
inconsistentes_monto = orders[
    orders['diferencia_monto'].abs() > 0.01
]

print('Total de registros:', len(orders))
print(
    'Registros con inconsistencias después del redondeo:',
    len(inconsistentes_monto)
)

# Mostrar todas las inconsistencias encontradas
display(
    inconsistentes_monto[
        [
            'id_pedido',
            'cantidad',
            'precio_unitario',
            'monto_descuento',
            'monto_total',
            'monto_calculado',
            'diferencia_monto'
        ]
    ]
)

Total de registros: 25000
Registros con inconsistencias después del redondeo: 1143

,id_pedido,cantidad,precio_unitario,monto_descuento,monto_total,monto_calculado,diferencia_monto
2,order_2,2.0,102.99,10.0,195.99,195.98,0.01
24,order_24,2.0,117.99,0.0,235.99,235.98,0.01
35,order_35,2.0,467.34,5.0,929.69,929.68,0.01
41,order_41,2.0,37.77,10.0,65.53,65.54,-0.01
136,order_136,2.0,211.05,15.0,407.09,407.10,-0.01
...,...,...,...,...,...,...,...
24889,order_24889,2.0,162.02,0.0,324.03,324.04,-0.01
24945,order_24945,2.0,395.22,0.0,790.43,790.44,-0.01
24967,order_24967,2.0,44.05,15.0,73.11,73.10,0.01
24970,order_24970,2.0,267.84,0.0,535.69,535.68,0.01
24990,order_24990,2.0,152.86,0.0,305.71,305.72,-0.01

In [20]:
# DISTRIBUCIÓN DE LAS DIFERENCIAS DE MONTO
# ======================

# Revisar los valores absolutos de diferencia
diferencias_abs = orders['diferencia_monto'].abs()

print('Registros con diferencia exactamente de 0:')
print((diferencias_abs == 0).sum())

print('\nRegistros con diferencia mayor a 0 y menor o igual a 0.01:')
print(
    (
        (diferencias_abs > 0) &
        (diferencias_abs <= 0.01)
    ).sum()
)

print('\nRegistros con diferencia mayor a 0.01 y menor o igual a 1:')
print(
    (
        (diferencias_abs > 0.01) &
        (diferencias_abs <= 1)
    ).sum()
)

print('\nRegistros con diferencia mayor a 1:')
print((diferencias_abs > 1).sum())

# Mostrar las diferencias distintas más frecuentes
print('\nFrecuencia de diferencias:')
display(
    orders['diferencia_monto']
    .round(2)
    .value_counts(dropna=False)
    .sort_index()
)

Registros con diferencia exactamente de 0:
18714

Registros con diferencia mayor a 0 y menor o igual a 0.01:
5093

Registros con diferencia mayor a 0.01 y menor o igual a 1:
1140

Registros con diferencia mayor a 1:
3

Frecuencia de diferencias:

-0.01      3157
 0.00     18714
 0.01      3076
 10.00        2
 20.00        1
 NaN         50
Name: diferencia_monto, dtype: int64

In [21]:
# ELIMINACIÓN DE REGISTROS CON CANTIDAD NEGATIVA
# ======================

# Número de registros antes de la limpieza
print('Registros antes de eliminar cantidades negativas:', len(orders))

# Eliminar registros con cantidad negativa
orders = orders[
    orders['cantidad'].isna() | (orders['cantidad'] >= 0)
].copy()

# Número de registros después de la limpieza
print('Registros después de eliminar cantidades negativas:', len(orders))

# Verificación
print('\nCantidades negativas restantes:')
print((orders['cantidad'] < 0).sum())

print('\nMontos totales negativos restantes:')
print((orders['monto_total'] < 0).sum())

Registros antes de eliminar cantidades negativas: 25000
Registros después de eliminar cantidades negativas: 24996

Cantidades negativas restantes:
0

Montos totales negativos restantes:
0

In [22]:
# REVISIÓN ACTUALIZADA DE VALORES AUSENTES
# ======================

print('VALORES AUSENTES EN ORDERS')
display(
    orders.isna().sum()
)

print('\nVALORES AUSENTES EN CATALOG')
display(
    catalog.isna().sum()
)

print('\nVALORES AUSENTES EN MARKETING')
display(
    marketing.isna().sum()
)

VALORES AUSENTES EN ORDERS

id_pedido                       0
id_usuario                      0
fecha_hora_pedido               0
pais                          296
dispositivo                    20
fuente_referencia              30
nombre_producto                30
categoria_producto             80
cantidad                       50
precio_unitario                50
monto_descuento                50
monto_total                     0
monto_calculado                50
diferencia_monto               50
monto_total_redondeado          0
monto_calculado_redondeado     50
dtype: int64

VALORES AUSENTES EN CATALOG

nombre_producto       0
categoria_producto    0
costo_unitario        0
proveedor             0
dtype: int64

VALORES AUSENTES EN MARKETING

fecha           0
pais            0
id_campaña      0
canal         101
gasto           0
dtype: int64

In [23]:
# REVISIÓN DE VALORES AUSENTES
# ======================

# Filas con valores numéricos ausentes
print('FILAS CON VALORES NUMÉRICOS AUSENTES')
display(
    orders[
        orders[
            ['cantidad', 'precio_unitario', 'monto_descuento']
        ].isna().any(axis=1)
    ][
        [
            'id_pedido',
            'id_usuario',
            'nombre_producto',
            'categoria_producto',
            'cantidad',
            'precio_unitario',
            'monto_descuento',
            'monto_total'
        ]
    ].head(20)
)

# Filas con nombre de producto ausente
print('\nFILAS CON NOMBRE DE PRODUCTO AUSENTE')
display(
    orders[
        orders['nombre_producto'].isna()
    ].head(10)
)

# Filas con categoría de producto ausente
print('\nFILAS CON CATEGORÍA DE PRODUCTO AUSENTE')
display(
    orders[
        orders['categoria_producto'].isna()
    ][
        [
            'id_pedido',
            'nombre_producto',
            'categoria_producto'
        ]
    ].head(20)
)

# Valores disponibles en la columna canal de MARKETING
print('\nVALORES DISPONIBLES EN CANAL')
display(
    marketing['canal'].value_counts(dropna=False)
)

FILAS CON VALORES NUMÉRICOS AUSENTES

,id_pedido,id_usuario,nombre_producto,categoria_producto,cantidad,precio_unitario,monto_descuento,monto_total
74,order_74,user_6172,Sneakers-Urban-42,NaN,NaN,NaN,NaN,595.85
75,order_75,user_6588,Sneakers-Urban-42,NaN,NaN,NaN,NaN,458.15
76,order_76,user_3193,Laptop-Gaming-16GB,NaN,NaN,NaN,NaN,319.75
77,order_77,user_775,Vacuum-Pro-Black,NaN,NaN,NaN,NaN,227.55
78,order_78,user_2702,Phone-Pro-128GB,NaN,NaN,NaN,NaN,432.39
79,order_79,user_6438,Sneakers-Urban-42,NaN,NaN,NaN,NaN,527.15
80,order_80,user_6790,Vacuum-Pro-Black,NaN,NaN,NaN,NaN,711.18
81,order_81,user_232,Tablet-Standard-64GB,NaN,NaN,NaN,NaN,41.08
82,order_82,user_5665,Sneakers-Urban-42,NaN,NaN,NaN,NaN,431.55
83,order_83,user_5225,Sneakers-Urban-42,NaN,NaN,NaN,NaN,279.35
84,order_84,user_5599,Laptop-Gaming-16GB,NaN,NaN,NaN,NaN,785.89
85,order_85,user_4051,Jacket-Winter-M,NaN,NaN,NaN,NaN,576.13
86,order_86,user_2260,Tablet-Standard-64GB,NaN,NaN,NaN,NaN,49.80
87,order_87,user_88,Tablet-Standard-64GB,NaN,NaN,NaN,NaN,143.11
88,order_88,user_7208,Blender-XL-Red,NaN,NaN,NaN,NaN,856.06
89,order_89,user_3453,Vacuum-Pro-Black,NaN,NaN,NaN,NaN,222.21
90,order_90,user_1399,Laptop-Gaming-16GB,NaN,NaN,NaN,NaN,85.71
91,order_91,user_7433,Sneakers-Urban-42,NaN,NaN,NaN,NaN,474.59
92,order_92,user_5356,Sneakers-Urban-42,NaN,NaN,NaN,NaN,271.43
93,order_93,user_5669,Blender-XL-Red,NaN,NaN,NaN,NaN,359.47

FILAS CON NOMBRE DE PRODUCTO AUSENTE

,id_pedido,id_usuario,fecha_hora_pedido,pais,dispositivo,fuente_referencia,nombre_producto,categoria_producto,cantidad,precio_unitario,monto_descuento,monto_total,monto_calculado,diferencia_monto,monto_total_redondeado,monto_calculado_redondeado
44,order_44,user_2899,2025-02-22,Colombia,desktop,NaN,NaN,NaN,1.0,318.38,5.0,313.38,313.38,0.00,313.38,313.38
45,order_45,user_6196,2025-02-10,Mexico,mobile,NaN,NaN,NaN,2.0,354.06,10.0,698.12,698.12,0.00,698.12,698.12
46,order_46,user_5815,2025-04-24,Mexico,mobile,NaN,NaN,NaN,1.0,359.31,10.0,349.31,349.31,0.00,349.31,349.31
47,order_47,user_406,2025-05-08,Colombia,mobile,NaN,NaN,NaN,2.0,476.78,0.0,953.56,953.56,0.00,953.56,953.56
48,order_48,user_6187,2025-01-26,Colombia,desktop,NaN,NaN,NaN,2.0,137.96,0.0,275.93,275.92,0.01,275.93,275.92
49,order_49,user_7225,2025-04-04,Argentina,desktop,NaN,NaN,NaN,2.0,433.76,0.0,867.53,867.52,0.01,867.53,867.52
50,order_50,user_1840,2025-02-05,Mexico,desktop,NaN,NaN,NaN,1.0,495.38,5.0,490.38,490.38,0.00,490.38,490.38
51,order_51,user_5998,2025-02-21,Mexico,desktop,NaN,NaN,NaN,2.0,382.94,0.0,765.89,765.88,0.01,765.89,765.88
52,order_52,user_5679,2025-04-17,Argentina,mobile,NaN,NaN,NaN,2.0,415.01,0.0,830.01,830.02,-0.01,830.01,830.02
53,order_53,user_5936,2025-01-02,Argentina,desktop,NaN,NaN,NaN,2.0,236.49,0.0,472.98,472.98,0.00,472.98,472.98

FILAS CON CATEGORÍA DE PRODUCTO AUSENTE

   id_pedido nombre_producto categoria_producto
44  order_44             NaN                NaN
45  order_45             NaN                NaN
46  order_46             NaN                NaN
47  order_47             NaN                NaN
48  order_48             NaN                NaN
49  order_49             NaN                NaN
50  order_50             NaN                NaN
51  order_51             NaN                NaN
52  order_52             NaN                NaN
53  order_53             NaN                NaN
54  order_54             NaN                NaN
55  order_55             NaN                NaN
56  order_56             NaN                NaN
57  order_57             NaN                NaN
58  order_58             NaN                NaN
59  order_59             NaN                NaN
60  order_60             NaN                NaN
61  order_61             NaN                NaN
62  order_62             NaN                NaN
63  order_63             NaN                NaN

VALORES DISPONIBLES EN CANAL

paid_search    507
organic        506
social         506
NaN            101
Name: canal, dtype: int64

In [26]:
# LIMPIEZA DE VARIABLES CATEGÓRICAS
# ======================

columnas_categoricas_orders = [
    'pais',
    'dispositivo',
    'fuente_referencia',
    'nombre_producto',
    'categoria_producto'
]

# Identificar valores ausentes como "Desconocido"
orders[columnas_categoricas_orders] = (
    orders[columnas_categoricas_orders]
    .fillna('Desconocido')
)

# Identificar canales ausentes
marketing['canal'] = marketing['canal'].fillna('Desconocido')

In [27]:
# ELIMINAR COLUMNAS TEMPORALES
# ======================

columnas_temporales = [
    'monto_calculado',
    'diferencia_monto',
    'monto_total_redondeado',
    'monto_calculado_redondeado'
]

orders = orders.drop(
    columns=columnas_temporales,
    errors='ignore'
)

In [28]:
# VALIDACIÓN FINAL
# ======================

print('REGISTROS FINALES')
print('ORDERS:', orders.shape)
print('CATALOG:', catalog.shape)
print('MARKETING:', marketing.shape)

print('\nVALORES AUSENTES FINALES')

print('\nORDERS')
print(orders.isna().sum())

print('\nCATALOG')
print(catalog.isna().sum())

print('\nMARKETING')
print(marketing.isna().sum())

REGISTROS FINALES
ORDERS: (24996, 12)
CATALOG: (7, 4)
MARKETING: (1620, 5)

VALORES AUSENTES FINALES

ORDERS
id_pedido              0
id_usuario             0
fecha_hora_pedido      0
pais                   0
dispositivo            0
fuente_referencia      0
nombre_producto        0
categoria_producto     0
cantidad              50
precio_unitario       50
monto_descuento       50
monto_total            0
dtype: int64

CATALOG
nombre_producto       0
categoria_producto    0
costo_unitario        0
proveedor             0
dtype: int64

MARKETING
fecha         0
pais          0
id_campaña    0
canal         0
gasto         0
dtype: int64

## Conclusión del Paso 1: preparación y calidad de los datos

Se revisaron los tres datasets correspondientes a pedidos, catálogo y marketing. Durante la preparación se eliminaron registros duplicados y se convirtieron las variables de fecha al formato adecuado para el análisis.

También se identificaron cuatro registros con cantidades y montos totales negativos. Debido a que estos valores no son consistentes con el análisis de pedidos, los cuatro registros fueron eliminados.

Se identificaron valores extremos en la variable cantidad, correspondientes a 10,000 y 20,000 unidades. Estos registros se conservaron debido a que no se encontró evidencia suficiente para corregirlos o eliminarlos de manera justificada. Por ello, deberán considerarse al interpretar indicadores que puedan verse influenciados por valores extremos.

Los valores ausentes en variables categóricas fueron identificados como Desconocido, con el objetivo de conservar los registros y mantener visible la ausencia de información. En las variables numéricas con información faltante no se imputaron valores, ya que no existía evidencia suficiente para estimarlos sin introducir supuestos.

Finalmente, se eliminaron las columnas temporales utilizadas durante la validación y se conservaron los datasets preparados para las siguientes etapas del análisis.

---
**📦 Exportación**: Una vez finalizada la limpieza, se exportan los datasets para utilizarlos en la última etapa del proyecto.

In [29]:
# exportar datasets
orders.to_csv('orders_clean.csv', index=False)
catalog.to_csv('catalog_clean.csv', index=False)
marketing.to_csv('marketing_clean.csv', index=False)

---

## 🔹 Paso 2: Analizar si el negocio es rentable

### 2.1 Cálculo de KPIs principales

**🎯 Objetivo:** Calcular los indicadores clave del negocio para evaluar ingresos, costos y rentabilidad.

Se usan los 3 datasets (`orders`, `catalog`, `marketing_spend`):

**📊 Parte 1: Rentabilidad del negocio**
- ¿Cuál es el ingreso total (revenue)? 
- ¿Cuál es el costo total? 
- ¿Cuánto se ha invertido en marketing? 
- ¿El negocio es rentable? (calcular profit)  

---

**📈 Parte 2: Comportamiento de ventas**
- ¿Cuál es el ticket promedio por orden? 
- ¿Cuál es la cantidad promedio de productos por orden? 
- ¿Cuál es el producto más vendido?
- ¿Cuánto se ha gastado en marketing por canal?

In [30]:
# PASO 2: ANÁLISIS DE RENTABILIDAD
# ======================

# Crear una copia para el análisis
profitability = orders.copy()

# Unir ORDERS con CATALOG usando el nombre del producto
profitability = profitability.merge(
    catalog[
        [
            'nombre_producto',
            'costo_unitario'
        ]
    ],
    on='nombre_producto',
    how='left'
)

# Revisar el resultado de la unión
print('Dimensiones de la tabla de rentabilidad:')
print(profitability.shape)

print('\nValores ausentes después de unir el catálogo:')
print(
    profitability[
        [
            'cantidad',
            'costo_unitario',
            'monto_total'
        ]
    ].isna().sum()
)

Dimensiones de la tabla de rentabilidad:
(24996, 13)

Valores ausentes después de unir el catálogo:
cantidad          50
costo_unitario    30
monto_total        0
dtype: int64

In [31]:
# KPIs DE RENTABILIDAD
# ======================

# Calcular costo total por pedido
profitability['costo_total'] = (
    profitability['cantidad'] *
    profitability['costo_unitario']
)

# Calcular ganancia por pedido
profitability['profit'] = (
    profitability['monto_total'] -
    profitability['costo_total']
)

# KPIs principales
revenue_total = profitability['monto_total'].sum()
costo_total = profitability['costo_total'].sum()
profit_total = profitability['profit'].sum()

# Margen de ganancia
margen_profit = (profit_total / revenue_total) * 100

print(f'Revenue total: ${revenue_total:,.2f}')
print(f'Costo total: ${costo_total:,.2f}')
print(f'Profit total: ${profit_total:,.2f}')
print(f'Margen de ganancia: {margen_profit:.2f}%')

Revenue total: $51,988,609.56
Costo total: $43,124,069.01
Profit total: $8,830,649.93
Margen de ganancia: 16.99%

In [32]:
# RENTABILIDAD POR SEGMENTOS
# ======================

def rentabilidad_segmento(columna):
    
    resultado = (
        profitability
        .groupby(columna, dropna=False)
        .agg(
            revenue=('monto_total', 'sum'),
            costo=('costo_total', 'sum'),
            profit=('profit', 'sum'),
            pedidos=('id_pedido', 'nunique')
        )
        .reset_index()
    )
    
    resultado['margen_profit_pct'] = (
        resultado['profit'] / resultado['revenue'] * 100
    )
    
    return resultado.sort_values('profit', ascending=False)


# Rentabilidad por país
rentabilidad_pais = rentabilidad_segmento('pais')

# Rentabilidad por categoría
rentabilidad_categoria = rentabilidad_segmento('categoria_producto')

# Rentabilidad por fuente de referencia
rentabilidad_fuente = rentabilidad_segmento('fuente_referencia')


print('RENTABILIDAD POR PAÍS')
display(rentabilidad_pais)

print('\nRENTABILIDAD POR CATEGORÍA')
display(rentabilidad_categoria)

print('\nRENTABILIDAD POR FUENTE DE REFERENCIA')
display(rentabilidad_fuente)

RENTABILIDAD POR PAÍS

,pais,revenue,costo,profit,pedidos,margen_profit_pct
0,Argentina,20413971.04,1.515548e+07,5245843.56,7259,25.697320
3,Mexico,18566255.79,1.518598e+07,3370279.56,7478,18.152715
1,Colombia,11059540.32,9.566741e+06,1482951.01,7481,13.408794
4,argentina,318676.57,1.145543e+05,203674.55,796,63.912622
5,colombia,319866.55,1.242895e+05,194852.67,823,60.916864
2,Desconocido,111988.05,4.370974e+04,68278.31,296,60.969282
6,mexico,1198311.24,2.933319e+06,-1735229.73,863,-144.806263

RENTABILIDAD POR CATEGORÍA

,categoria_producto,revenue,costo,profit,pedidos,margen_profit_pct
1,Electronica,45549430.40,4.062009e+07,4929341.83,8275,10.821962
2,Hogar,3232626.44,1.213437e+06,2019189.48,8346,62.462815
3,Moda,3172662.10,1.290543e+06,1882118.62,8295,59.323009
0,Desconocido,33890.62,0.000000e+00,0.00,80,0.000000

RENTABILIDAD POR FUENTE DE REFERENCIA

,fuente_referencia,revenue,costo,profit,pedidos,margen_profit_pct
2,paid_search,25234358.00,2.088856e+07,4338921.01,8278,17.194497
1,organic,12509475.66,9.695574e+06,2805154.39,8287,22.424236
3,social,14232513.28,1.253994e+07,1686574.53,8401,11.850153
0,Desconocido,12262.62,0.000000e+00,0.00,30,0.000000

In [33]:
# NORMALIZAR NOMBRES DE PAÍS
# ======================

# Estandarizar país en los datasets
orders['pais'] = orders['pais'].str.strip().str.title()
marketing['pais'] = marketing['pais'].str.strip().str.title()

# Actualizar también la tabla usada en rentabilidad
profitability['pais'] = profitability['pais'].str.strip().str.title()

# Recalcular rentabilidad por país
rentabilidad_pais = rentabilidad_segmento('pais')

print('RENTABILIDAD POR PAÍS - CORREGIDA')
display(rentabilidad_pais)

RENTABILIDAD POR PAÍS - CORREGIDA

,pais,revenue,costo,profit,pedidos,margen_profit_pct
0,Argentina,20732647.61,1.527003e+07,5449518.11,8055,26.284719
1,Colombia,11379406.87,9.691030e+06,1677803.68,8304,14.744210
3,Mexico,19764567.03,1.811930e+07,1635049.83,8341,8.272632
2,Desconocido,111988.05,4.370974e+04,68278.31,296,60.969282

## Conclusiones — Paso 2: Análisis de rentabilidad

El negocio registró ingresos totales (revenue) de $51.99 millones. Para los pedidos en los que fue posible calcular los costos, se obtuvo un costo total de aproximadamente $43.12 millones y un profit de $8.83 millones. El margen de ganancia calculado fue de aproximadamente 16.99%, lo que muestra un resultado positivo en el período analizado.

Rentabilidad por país

Argentina fue el mercado con mayor profit, con aproximadamente $5.45 millones, y un margen de 26.28%. Colombia generó aproximadamente $1.68 millones de profit, con un margen de 14.74%, mientras que México registró aproximadamente $1.64 millones, con un margen de 8.27%.

Entre los países identificados, Argentina presentó tanto el mayor profit absoluto como el mayor margen de ganancia.

Rentabilidad por categoría

Electrónica generó el mayor profit absoluto, con aproximadamente $4.93 millones. Sin embargo, su margen fue de 10.82%.

Por otro lado, Hogar y Moda presentaron márgenes considerablemente mayores, de 62.46% y 59.32%, respectivamente. Esto muestra que el segmento con mayor profit absoluto no necesariamente es el que presenta el mayor margen.

Rentabilidad por fuente de referencia

Paid search generó el mayor profit absoluto, con aproximadamente $4.34 millones, seguido de organic con $2.81 millones y social con $1.69 millones.

En términos de margen, organic presentó el mejor resultado con 22.42%, seguido de paid search con 17.19% y social con 11.85%.

Conclusión

Los resultados muestran un profit positivo en el período analizado. Argentina destaca entre los países identificados por su nivel de profit y margen; Electrónica aporta el mayor profit por categoría, mientras que Hogar y Moda presentan mayores márgenes. En adquisición, paid search aporta el mayor profit absoluto, mientras que organic presenta el mayor margen.

Como limitación, algunos pedidos contienen información insuficiente para determinar su costo. Estos registros se conservaron sin imputar valores, por lo que los resultados de costo, profit y margen deben interpretarse considerando esta cobertura incompleta.

---

## 🔹 Paso 3: Entender dónde se pierden los usuarios (funnel de conversión)

**🎯 Objetivo:** Analizar el comportamiento de los usuarios para identificar en qué etapa del proceso se pierden.


⚙️**Conexión a la base de datos**:  
Se ejecuta la línea de configuración para conectar con la base de datos y aplicar consultas SQL en la tabla **events**.

---

**📊 Parte 1: Construcción del funnel**
- ¿Cuántos usuarios llegan a cada etapa del funnel?  
- Se calcula el número de usuarios únicos por `nombre_evento`  
- Se ordenan los eventos según el flujo del usuario  

---

**📉 Parte 2: Análisis de conversión**
- Se calcula la tasa de conversión entre cada paso del funnel  
- Se identifica en qué etapa se pierde la mayor cantidad de usuarios  
- ¿Cuál es la tasa de conversión final?
---

In [35]:
import pandas as pd
from sqlalchemy import create_engine

# ======================
# Conexión (NO modificar)
# ======================
db_config = {
    'user': 'practicum_student',
    'pwd': 'QnmDH8Sc2TQLvy2G3Vvh7',
    'host': 'yp-trainers-practicum.cluster-czs0gxyx2d8w.us-east-1.rds.amazonaws.com',
    'port': 5432,
    'db': 'data-analyst-production-db-en'
}

connection_string = 'postgresql://{}:{}@{}:{}/{}'.format(
    db_config['user'],
    db_config['pwd'],
    db_config['host'],
    db_config['port'],
    db_config['db']
)

engine = create_engine(connection_string, connect_args={'sslmode':'require'})

In [36]:
# Explorar tabla events
# =========================
query_events = '''
SELECT *
FROM events;
'''
events = pd.read_sql(query_events, con=engine)
events.head()

,id_usuario,id_sesion,nombre_evento,timestamp_evento,pais,dispositivo,fuente_referencia,categoria_producto
0,user_6772,6a97f2af-32ae-4186-8c92-04025be1a27b,first_visit,2025-05-17,Colombia,desktop,organic,Moda
1,user_5883,369b767c-1c33-4b2f-a652-c7c0ef92cfc9,add_to_cart,2025-02-23,Mexico,mobile,social,Hogar
2,user_5946,60039041-e78b-474c-87b3-c0b7e9c30708,add_payment_info,2025-05-15,Colombia,desktop,social,Electronica
3,user_827,18252a64-f389-4ef7-9e58-dadad4a3491e,purchase,2025-03-31,Mexico,mobile,social,Moda
4,user_2361,221b364e-cdc5-4668-b698-18d5ba849a67,first_visit,2025-01-22,Argentina,desktop,paid_search,Electronica

In [37]:
# EVENTOS DISPONIBLES
# ======================

query = """
SELECT
    nombre_evento,
    COUNT(*) AS total_eventos
FROM events
GROUP BY nombre_evento
ORDER BY total_eventos DESC;
"""

tipos_eventos = pd.read_sql(query, con=engine)

display(tipos_eventos)

      nombre_evento  total_eventos
0       first_visit          29957
1       add_to_cart          24157
2       select_item          23887
3    begin_checkout          17971
4  add_payment_info          12018
5          purchase          12010

In [38]:
# PARTE 1: Totales del funnel
# ======================


query_totals = '''
SELECT
    nombre_evento,
    COUNT(DISTINCT id_usuario) AS usuarios
FROM events
GROUP BY nombre_evento
ORDER BY CASE nombre_evento
    WHEN 'first_visit' THEN 1
    WHEN 'select_item' THEN 2
    WHEN 'add_to_cart' THEN 3
    WHEN 'begin_checkout' THEN 4
    WHEN 'add_payment_info' THEN 5
    WHEN 'purchase' THEN 6
END;
'''

totals = pd.read_sql(query_totals, con=engine)
totals

      nombre_evento  usuarios
0       first_visit      7796
1       select_item      7582
2       add_to_cart      7634
3    begin_checkout      7208
4  add_payment_info      6250
5          purchase      6240

In [39]:
# PARTE 2: Conversiones
# ======================

query_conversion = '''
WITH funnel AS (
    SELECT
        nombre_evento,
        COUNT(DISTINCT id_usuario) AS usuarios,
        CASE nombre_evento
            WHEN 'first_visit' THEN 1
            WHEN 'select_item' THEN 2
            WHEN 'add_to_cart' THEN 3
            WHEN 'begin_checkout' THEN 4
            WHEN 'add_payment_info' THEN 5
            WHEN 'purchase' THEN 6
        END AS etapa
    FROM events
    GROUP BY nombre_evento
),

conversiones AS (
    SELECT
        nombre_evento,
        usuarios,
        etapa,
        LAG(usuarios) OVER (ORDER BY etapa) AS usuarios_etapa_anterior
    FROM funnel
)

SELECT
    nombre_evento,
    usuarios,
    ROUND(
        usuarios * 100.0 /
        FIRST_VALUE(usuarios) OVER (ORDER BY etapa),
        2
    ) AS conversion_desde_inicio_pct,
    ROUND(
        usuarios * 100.0 / usuarios_etapa_anterior,
        2
    ) AS conversion_etapa_pct,
    ROUND(
        100 - (usuarios * 100.0 / usuarios_etapa_anterior),
        2
    ) AS drop_off_pct
FROM conversiones
ORDER BY etapa;
'''

conversion = pd.read_sql(query_conversion, con=engine)
conversion

,nombre_evento,usuarios,conversion_desde_inicio_pct,conversion_etapa_pct,drop_off_pct
0,first_visit,7796,100.00,NaN,NaN
1,select_item,7582,97.26,97.26,2.74
2,add_to_cart,7634,97.92,100.69,-0.69
3,begin_checkout,7208,92.46,94.42,5.58
4,add_payment_info,6250,80.17,86.71,13.29
5,purchase,6240,80.04,99.84,0.16

## Conclusiones — Paso 3: Funnel de conversión

El funnel muestra una conversión alta a lo largo del recorrido del usuario. De los 7,796 usuarios que registraron first_visit, 6,240 llegaron a purchase, lo que representa una conversión acumulada aproximada de 80.04%.

El mayor punto de abandono se encuentra entre begin_checkout y add_payment_info, donde la conversión entre etapas fue de 86.71% y el drop-off alcanzó 13.29%.

El resto de las etapas presenta pérdidas menores, especialmente entre add_payment_info y purchase, donde la conversión fue de 99.84%.

También se observa que add_to_cart tiene ligeramente más usuarios únicos que select_item. Esto indica que los eventos observados no siguen una secuencia estrictamente decreciente para todos los usuarios, por lo que esta diferencia debe considerarse una limitación al interpretar el funnel.

En términos de negocio, el principal punto a revisar se encuentra en la transición entre el inicio del checkout y el registro de información de pago, ya que concentra la mayor pérdida de usuarios del proceso.

---

## 🔹 Paso 4: Evaluar si los usuarios regresan (retención por cohortes)

**🎯 Objetivo:** Analizar la retención de usuarios para entender si regresan después de registrarse.

**Tablas**

- `users` 
- `user_activity` 

---
1. Se identifica la cohorte de cada usuario según el **mes de registro**.


2. Se calcula la retención semanal: cuántos usuarios **se mantienen activos** en cada semana desde su registro.
   - `retenido_w1`: usuarios activos en la semana 1  
   - `retenido_w2`: usuarios activos en la semana 2  
   - `retenido_w3`: usuarios activos en la semana 3  


3. Se calcula el porcentaje de retención para cada semana, dividiendo los usuarios retenidos entre los clientes iniciales de la cohorte:  
   - `semana_1`: porcentaje de usuarios retenidos en la semana 1  
   - `semana_2`: porcentaje de usuarios retenidos en la semana 2  
   - `semana_3`: porcentaje de usuarios retenidos en la semana 3  

Se revisa que la columna de fecha esté en formato correcto (`DATE`).  
Se realiza la conversión usando: `CAST(fecha_registro AS DATE)`

In [40]:
# Explorar tabla users
# =========================
query_users = '''
SELECT *
FROM users;
'''
users = pd.read_sql(query_users, con=engine)
users.head(3)

  id_usuario fecha_registro       país dispositivo tipo_plan
0     user_0     2025-01-29     Mexico      mobile      free
1     user_1     2025-01-07     Mexico      mobile      free
2     user_2     2025-03-12  Argentina      mobile      free

In [41]:
# Explorar tabla user_activity
# =========================
query_activity = '''
SELECT *
FROM user_activity;
'''

user_activity = pd.read_sql(query_activity, con=engine)

user_activity.head(3)

  id_usuario fecha_actividad  dias_despues_registro  activo
0     user_0      2025-02-05                      7       0
1     user_0      2025-02-12                     14       1
2     user_0      2025-02-19                     21       1

In [43]:
# Retención por cohortes
# ======================

query_cohort_retention_final = '''
WITH cohortes AS (
    SELECT
        id_usuario,
        DATE_TRUNC('month', fecha_registro::date)::date AS cohorte
    FROM users
),

tamano_cohorte AS (
    SELECT
        cohorte,
        COUNT(DISTINCT id_usuario) AS usuarios_cohorte
    FROM cohortes
    GROUP BY cohorte
),

usuarios_activos AS (
    SELECT
        c.cohorte,
        ua.dias_despues_registro,
        COUNT(DISTINCT ua.id_usuario) AS usuarios_activos
    FROM cohortes c
    JOIN user_activity ua
        ON c.id_usuario = ua.id_usuario
    WHERE ua.activo = 1
    GROUP BY
        c.cohorte,
        ua.dias_despues_registro
)

SELECT
    a.cohorte,
    a.dias_despues_registro,
    t.usuarios_cohorte,
    a.usuarios_activos,
    ROUND(
        a.usuarios_activos * 100.0 / t.usuarios_cohorte,
        2
    ) AS retencion_pct
FROM usuarios_activos a
JOIN tamano_cohorte t
    ON a.cohorte = t.cohorte
ORDER BY
    a.cohorte,
    a.dias_despues_registro;
'''

cohorte_final = pd.read_sql(
    query_cohort_retention_final,
    con=engine
)

cohorte_final

,cohorte,dias_despues_registro,usuarios_cohorte,usuarios_activos,retencion_pct
0,2025-01-01,7,1627,697,42.84
1,2025-01-01,14,1627,668,41.06
2,2025-01-01,21,1627,656,40.32
3,2025-01-01,28,1627,671,41.24
4,2025-02-01,7,1444,611,42.31
5,2025-02-01,14,1444,609,42.17
6,2025-02-01,21,1444,635,43.98
7,2025-02-01,28,1444,575,39.82
8,2025-03-01,7,1636,677,41.38
9,2025-03-01,14,1636,705,43.09
10,2025-03-01,21,1636,690,42.18
11,2025-03-01,28,1636,673,41.14
12,2025-04-01,7,1606,680,42.34
13,2025-04-01,14,1606,697,43.40
14,2025-04-01,21,1606,663,41.28
15,2025-04-01,28,1606,652,40.60
16,2025-05-01,7,1687,695,41.20
17,2025-05-01,14,1687,676,40.07
18,2025-05-01,21,1687,706,41.85
19,2025-05-01,28,1687,679,40.25

## Conclusiones — Paso 4: Retención por cohortes

El análisis de cohortes muestra que la retención de usuarios se mantiene relativamente estable durante las primeras cuatro semanas posteriores al registro.

En las cohortes analizadas, la retención se encuentra aproximadamente entre 40% y 44% en los días 7, 14, 21 y 28.

No se observa una disminución continua y pronunciada conforme pasan las semanas. En varias cohortes incluso se presentan ligeros incrementos en algunos períodos, lo que indica variaciones en la actividad de los usuarios entre semanas.

Entre los valores más altos se encuentra la cohorte de febrero en el día 21, con una retención de 43.98%. Por otro lado, uno de los valores más bajos corresponde a la misma cohorte en el día 28, con 39.82%.

En términos generales, alrededor de cuatro de cada diez usuarios registrados permanecen activos en los períodos analizados. Esto sugiere que existe una base recurrente de usuarios, aunque también hay una proporción importante que no presenta actividad en cada período de seguimiento.

---

## 🔹 Paso 5: Validar si los cambios generan impacto (test estadístico)

🎯 **Objetivo:** Evaluar si la modificación en la UI del checkout impacta la **tasa de conversión de compra**.

---

1. **Analizar el dataset** `experiment_checkout_ui.csv` para identificar la métrica principal **conversion**.
   - La métrica **conversion** es 1 si el usuario completó la compra, 0 si no.    
2. **Plantear la hipótesis estadística**     
3. **Aplicar el test estadístico adecuado** 
4. **Interpretar el resultado**

---
Hipótesis estadística
   - **H₀ (Hipótesis nula):** No existe una diferencia estadísticamente significativa en la tasa de conversión de compra entre el grupo control y el grupo tratamiento.
   - **H₁ (Hipótesis alternativa):** Existe una diferencia estadísticamente significativa en la tasa de conversión de compra entre el grupo control y el grupo tratamiento.
   
**Test estadístico:** Prueba Z de dos proporciones.
**Nivel de significancia alpha:** α = 0.05.

In [44]:
# PASO 5: EXPERIMENTO A/B
# Cargar dataset
# ======================

url_experiment = 'https://practicum-content.s3.amazonaws.com/datasets/experiment_checkout_ui.csv'

experiment = pd.read_csv(url_experiment)

experiment.head()

,id_usuario,variante,convirtio,dispositivo,pais,duracion_sesion,timestamp
0,exp_user_0,tratamiento,0,mobile,Argentina,114.41,2025-03-28
1,exp_user_1,tratamiento,0,desktop,Mexico,170.03,2025-01-15
2,exp_user_2,control,1,mobile,Colombia,140.21,2025-03-18
3,exp_user_3,tratamiento,0,mobile,Colombia,151.45,2025-06-03
4,exp_user_4,tratamiento,0,desktop,Mexico,299.96,2025-01-12

In [45]:
# COMPARACIÓN CONTROL VS TRATAMIENTO
# ======================

resumen_ab = (
    experiment
    .groupby('variante')
    .agg(
        usuarios=('id_usuario', 'nunique'),
        conversiones=('convirtio', 'sum'),
        tasa_conversion=('convirtio', 'mean')
    )
    .reset_index()
)

# Convertir la tasa a porcentaje
resumen_ab['tasa_conversion_pct'] = (
    resumen_ab['tasa_conversion'] * 100
)

display(resumen_ab)

      variante  usuarios  conversiones  tasa_conversion  tasa_conversion_pct
0      control      4965           779         0.156898            15.689829
1  tratamiento      5035           820         0.162860            16.285998

In [46]:
# PRUEBA Z DE DOS PROPORCIONES
# ======================

from statsmodels.stats.proportion import proportions_ztest

# Conversiones de cada grupo
conversiones = [
    experiment.loc[
        experiment['variante'] == 'control',
        'convirtio'
    ].sum(),
    
    experiment.loc[
        experiment['variante'] == 'tratamiento',
        'convirtio'
    ].sum()
]

# Número de usuarios de cada grupo
usuarios = [
    experiment.loc[
        experiment['variante'] == 'control',
        'id_usuario'
    ].nunique(),
    
    experiment.loc[
        experiment['variante'] == 'tratamiento',
        'id_usuario'
    ].nunique()
]

# Prueba Z
z_stat, p_value = proportions_ztest(
    count=conversiones,
    nobs=usuarios
)

alpha = 0.05

print(f'Estadístico Z: {z_stat:.4f}')
print(f'P-value: {p_value:.4f}')

if p_value < alpha:
    print('Resultado: se rechaza H0.')
    print('Existe una diferencia estadísticamente significativa entre las variantes.')
else:
    print('Resultado: no se rechaza H0.')
    print('No hay evidencia suficiente de una diferencia estadísticamente significativa.')

Estadístico Z: -0.8133
P-value: 0.4161
Resultado: no se rechaza H0.
No hay evidencia suficiente de una diferencia estadísticamente significativa.

**Resultado**
Tasa de conversión del grupo control: 15.69%
Tasa de conversión del grupo tratamiento: 16.29%
Estadístico Z: -0.8133
p-value: 0.4161

Como el p-value (0.4161) es mayor que α (0.05), no se rechaza la hipótesis nula.

**Interpretación y recomendación**

Aunque el grupo tratamiento presentó una tasa de conversión ligeramente superior a la del grupo control, la diferencia observada no es estadísticamente significativa.

Por lo tanto, no existe evidencia suficiente para concluir que la modificación en la interfaz del checkout mejore la conversión de compra.

Se recomienda no implementar el tratamiento de forma general basándose únicamente en este experimento. Si el cambio continúa siendo de interés para el negocio, sería conveniente realizar pruebas adicionales antes de tomar una decisión definitiva.

In [47]:
orders.to_csv('orders_clean.csv', index=False)
catalog.to_csv('catalog_clean.csv', index=False)
marketing.to_csv('marketing_clean.csv', index=False)

print('Archivos finales exportados correctamente.')

Archivos finales exportados correctamente.

---

## 🔹 Paso 6: Comunicar los resultados (Dashboard en BI)

🎯 **Objetivo**:  
Crear un dashboard que muestre de manera clara y visual los resultados del análisis de ventas, costos, marketing y conversión. 

Se usarán los CSVs limpios del Paso 1:

- `orders_clean.csv`  
- `catalog_clean.csv`  
- `marketing_clean.csv`

---

1️⃣ Preparación de los datos
1. Cargar los CSVs en Power BI o Tableau.
2. Revisar relaciones:
   - `orders.nombre_producto` → `catalog.nombre_producto`
   - `orders.fecha_pedido` → tabla de fechas (crear calendario para análisis temporal)
   - `orders.fecha_pedido` → `dim_fecha.date`
3. Crear columnas calculadas necesarias
4. Crear tabla de fechas para poder calcular comparaciones YTD, YoY o períodos anteriores (`Previous Year`, `Previous Month`).

---

2️⃣ Dashboard 1: Overview Ejecutivo
**KPIs principales a mostrar:**
- Revenue total
- Profit total
- Gasto total en marketing
- Ticket promedio
- Cantidad promedio de productos por orden

**Visualizaciones sugeridas:**
- Tarjetas KPI para revenue, profit y gasto marketing
- Gráfico de líneas: evolución mensual de revenue o profit
- Gráfico de líneas YTD
- Gráfico de barras: revenue y profit por producto o categoría

---

 3️⃣ Dashboard 2: Detalle / Drill-through  
**Objetivo:** Permitir explorar los datos desde el KPI general hasta cada orden o producto.

**Visualizaciones sugeridas:**
- Tabla detallada de órdenes con:
  - producto, cantidad, revenue, cost, profit
  - color condicional (profit negativo en rojo, positivo en verde)
- Gráfico de barras por producto con medida `cantidad vendida`
- Drill-through: seleccionar un producto y ver todos los pedidos relacionados
- Filtros por fecha, categoría de producto, etc

---

## 🚀 Entrega Final

Comparte el acceso a tu Dashboard para revisión.   
Puedes entregar el Dashboard utilizando **Power BI o Tableau**.

Incluye **uno de los siguientes**:

- 🔗 Link público del dashboard publicado en **Power BI Service o Tableau Public / Tableau Cloud**
- 🔗 Link de **Google Drive o OneDrive** con el archivo del proyecto (`.pbix`) y los 3 csvs limpios.


### 📎 Enlace del Dashboard

In [ ]:
# (Pega aquí tu link)
# link de power bi o tableau
# link de one drive / google drive